### ISSUE TITLE
can not be compiled

### ISSUE THREAD

**Issue by MttAI-dev** [DuelistRag3/WoWarriors#1]
**Description:**
When compiling core it makes 3 errors on smart AI and ect.
**Current behaviour:**
Shows 3 errors and no core created

**Project(s): <-- Mandatory**

- [ ] Issue found playing in Live Ashamane Private Server.
- [+] Issue found in a compiled master repo from Git.

**TC rev. hash/commit:**

**Comment by DuelistRag3** [comment]
Yes i know, as of time issues i wasn´t able to merge all changes, so its not compile error, maybe i get the time tommorow, i will close your issue as soon its done and compile ready :)
