### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mcsescott** [DuelistRag3/WoWarriors#16]
Downloaded latest commit this morning.  I am using CMake 2.16, BOOST 1.66, and VS2019, was unable to compile.

No errors in CMake, x64, but then failed to compile scripts.vcxproj and worldserver, tried both Release x64 and RelwithDebInfo x64.

**Comment by DuelistRag3** [comment]
can you post the error log please

**Comment by DuelistRag3** [comment]
Try the latest commit pls

**Comment by mcsescott** [comment]
OK, as I was trying it again you updated the commit.  Here is the Visual Studio log from my build of 6f9d818c

[DR3 VS Build Error.txt](https://github.com/DuelistRag3/WoWarriors/files/4658731/DR3.VS.Build.Error.txt)


I will try with the latest commit now.

**Comment by DuelistRag3** [comment]
yes, my latest commit should fix this, i accedantialy had DeathComesFromOnHigh quest line 2 times in the spell_quest cpp

**Comment by mcsescott** [comment]
Confirmed.  Build succeeded.  I'll test out the server in the next day or so... 

Thanks.

**Comment by DuelistRag3** [comment]
good to help, it might give you database crashes

**Comment by DuelistRag3** [comment]
i will patch these issues when i have time
