### ISSUE TITLE
PANDAREN DK

### ISSUE THREAD

**Issue by MttAI-dev** [DuelistRag3/WoWarriors#24]
just wanted to know Pandaren DK not egsist there it will be fixed and when?

**Comment by DuelistRag3** [comment]
Will look into that soon, panda dk´s are buggy atm, they produce a nothing to dispell error when casting

**Comment by MttAI-dev** [comment]
also do u have discord to talk with you?

**Comment by DuelistRag3** [comment]
Yes, if I'm right it should be linked at the bottom of the readme

**Comment by DuelistRag3** [comment]
Ok, it's not, I will add this later, when I'm home from work, you can access the discord over our website, at the bottom

**Comment by Thordekk** [comment]
The nothing to dispell error when casting i think i have the fix, its easy i have to test
