### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by firelook** [DuelistRag3/WoWarriors#25]
version as of committed 0c075c3 7 days ago
Windows 10
compilation Vs 2019

when I compile I have : 
`
Severity	Code	Description	Project	File	Line	Suppression State
Warning	RC4005	'_WIN32_WINNT' : redefinition	libcurl	D:\users_sys\games\wow\mangos\git\WoWarriors\bin\dep\cpr\opt\curl\lib\RC	1	
Warning	C4312	'reinterpret_cast': conversion from 'unsigned long' to 'const char *' of greater size	cpr	D:\users_sys\games\wow\mangos\git\WoWarriors\dep\cpr\cpr\session.cpp	197	
Warning	C4312	'reinterpret_cast': conversion from 'const unsigned long' to 'const char *' of greater size	cpr	D:\users_sys\games\wow\mangos\git\WoWarriors\dep\cpr\cpr\session.cpp	229	
Error	LNK2019	unresolved external symbol "void __cdecl AddSC_export_commandscript(void)" (?AddSC_export_commandscript@@YAXXZ) referenced in function "void __cdecl AddCommandsScripts(void)" (?AddCommandsScripts@@YAXXZ)	worldserver	D:\users_sys\games\wow\mangos\git\WoWarriors\bin\src\server\worldserver\scripts.lib(cs_script_loader.obj)	1	
Error	LNK1120	1 unresolved externals	worldserver	D:\users_sys\games\wow\mangos\git\WoWarriors\bin\bin\RelWithDebInfo\worldserver.exe	1	
`

**Comment by DuelistRag3** [comment]
Thats new to me, can you list, which externals you use?

**Comment by firelook** [comment]
what do you mean : 
boost c:/local/boost_1_67_0
cmake 3.17
lib : D:/OpenSSL-Win64_110l/lib/VC/libcrypto64MDd.lib
mysql C:/wamp64/bin/mysql/mysql5.7.21/include

**Comment by DuelistRag3** [comment]
Try with boost 1_66, some users reporting issues with boost higher than 66, including me

**Comment by firelook** [comment]
trinity and Ashamanecore are working well with this boost version
I suspect something else

**Comment by DuelistRag3** [comment]
let me quickly do a build with this version, my last build is over a week old, give me 30 mins

**Comment by DuelistRag3** [comment]
and this core is basically ashamane core with some small additions

**Comment by DuelistRag3** [comment]
nvmd, found the error, give me a second
