### ISSUE TITLE
database

### ISSUE THREAD

**Issue by firelook** [DuelistRag3/WoWarriors#26]
I am trying to update from scratch the game.
SI download ADB_world_820.00.sql + hotfixes and let the game running, but after some basic updates, I have
`[1146] La table 'wowarriors.updates_include' n'existe pas
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.`

IS it possible to have a clean up to date database, with  less sql updates ?

**Comment by DuelistRag3** [comment]
you have to manually create this table, i will fix this tomorrow, clean your database, let the programm create the 4 needed databases and then create updates_include insite every database. Or wait for the fix tomorrow and beginn with a fresh database, also your world database need the name ashamane_world, otherwise it wont get auto populated, thats a thing i will also fix tomorrow

**Comment by firelook** [comment]
I wait the fix, so I will be able to confirm your modification

**Comment by DuelistRag3** [comment]
can you post the log section where it says, which file it tried to update?

**Comment by firelook** [comment]
`TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release, Static) (worldserver-daemon)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file E:/games/wow/mangos/WoWarriors/worldserver.conf.
Using SSL version: OpenSSL 1.1.0l  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
Using Boost version: 1.67.0
Database World is empty, auto populating it...
>> Applying 'ADB_world_820.00.sql'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Done!
Database Hotfixes is empty, auto populating it...
>> Applying 'ADB_hotfixes_820.00.sql'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Done!
Updating Auth database...
DBUpdater: Given update include directory "D:/users_sys/games/wow/mangos/git/WoWarriors/sql/bfacoren/updates/auth" does not exist, skipped!
>> The file '2017_12_31_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_11_11_01_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_05_24_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_01_02_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_12_30_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2017_12_30_01_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_02_18_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_02_28_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_02_19_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_03_14_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_06_22_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_04_06_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_05_13_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_06_14_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2018_06_29_00_auth.sql' was applied to the database, but is missing in your update directory now!
>> The file '2020_04_30_00_auth.sql' was applied to the database, but is missing in your update directory now!
Cleanup is disabled! There were  16 dirty files applied to your database, but they are now missing in your source directory!
>> Auth database is up-to-date! Containing 1 new and 15 archived updates.
Updating Character database...
>> Applying update "2017_05_03_class_hall_garrison_1.sql" '73712F2'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2017_05_03_class_hall_garrison_2.sql" '2E93F5D'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2017_05_15_char_world_quest.sql" '6BC4128'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2017_11_17_01_characters_xprate.sql" 'C5435DC'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2017_12_20_01_characters_log_gm.sql" '8857548'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_01_07_00_charactes_pvp_talents.sql" '41DFE9B'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_01_13_01_charactes_pets.sql" '7437B62'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_02_02_01_character_shop.sql" '0A8138A'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_02_16_01_character_recovery.sql" 'C4FE203'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_02_18_01_characters.sql" 'B7EC9FD'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_02_18_02_characters.sql" '75FA162'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_04_04_01_characters.sql" '53CFC47'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_04_24_01_characters.sql" '052AB4D'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_05_18_00_charactes_world_quest.sql" '67EFD0D'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_06_13_01_characters.sql" '9C3B4EA'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_06_25_01_characters_archaeology.sql" 'C508912'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_07_27_01_characters_garrison.sql" '166F7D2'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_07_28_00_characters.sql" '31F66AE'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_10_08_01_characters_arena.sql" 'B747A63'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_10_08_02_characters_currency.sql" 'CECFED9'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_12_02_01_characters_archaeology.sql" 'B4522B1'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2018_12_02_02_characters_azeriteitems.sql" '9BE3A78'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> Applying update "2019_06_25_00_characters.sql" 'B8CBF79'...
mysql: [Warning] Using a password on the command line interface can be insecure.


>> The file '2020_04_26_00_characters_2017_04_12_00_characters.sql' was applied to the database, but is missing in your update directory now!
>> The file '2020_04_24_00_characters.sql' was applied to the database, but is missing in your update directory now!
>> The file '2020_04_25_00_characters_2017_04_03_00_characters.sql' was applied to the database, but is missing in your update directory now!
>> The file '2020_04_26_01_characters_2017_04_12_01_characters.sql' was applied to the database, but is missing in your update directory now!
Cleanup is disabled! There were  4 dirty files applied to your database, but they are now missing in your source directory!
>> Applied 23 queries. Containing 4 new and 0 archived updates.
Updating World database...
`


`[1146] La table 'wowarriors.updates_include' n'existe pas
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
`

**Comment by DuelistRag3** [comment]
Issue closed with latest database release, pls download it and beginn with a fresh database https://github.com/DuelistRag3/WoWarriors/releases/tag/8.3_07_13
