### ISSUE TITLE
MagniRealm_Database_2020_07_13 / 8.3.0

### ISSUE THREAD

**Issue by firelook** [DuelistRag3/WoWarriors#27]
If I understand correctly I should see ADB_world_830.00.sql and ADB_hotfixes_830.00.sql, isn't it ?
but I see only the code zip from github ?
am I wrong please ?

**Comment by DuelistRag3** [comment]
Thats because i may have forgoten to link the file :P

**Comment by DuelistRag3** [comment]
now it should be linked properly and you should be able to download
