### ISSUE TITLE
sql from scratch

### ISSUE THREAD

**Issue by firelook** [DuelistRag3/WoWarriors#28]
now my error is : 
`[1146] La table 'wowarriors.updates_include' n'existe pas
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
[1146] La table 'wowarriors_hotfixes.updates_include' n'existe pas
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
`

after
`>> Applying update "2020_06_20_06_world.sql" 'ECB7C05'...
mysql: [Warning] Using a password on the command line interface can be insecure.

>> Applied 78 queries. Containing 109 new and 0 archived updates.
Updating Hotfixes database...
`

**Comment by firelook** [comment]
I have not seen you have hardcoded a database inside the sql

**Comment by DuelistRag3** [comment]
ah i´m stupid, the hotfix has it also, i will remove the hardcode
