### ISSUE TITLE
Man kann sich nicht auf der Website registrieren!

### ISSUE THREAD

**Issue by warlord7111** [DuelistRag3/WoWarriors#9]
A Database Error Occurred
Error Number: 1364

Field 'activate' doesn't have a default value

INSERT INTO battlenet_accounts (id, email, sha_pass_hash, last_ip, joindate) VALUES ('326', '', '48F588A63A772ADCF446F893E3462A9633B749E17AEA0E81DC89C3BE7893A916', '88.130.53.144', '2020-05-08')

Filename: /var/www/html/models/external_account_model.php

Line Number: 149

**Comment by DuelistRag3** [comment]
Hey, actually wirst du registriert, aber der fehler kommt halt, einfach erstmall ignorieren, wird gefixed

**Comment by warlord7111** [comment]
Registrierung und Login über die Website funktioniert.
ABER Login über den Client funktioniert nicht.
D.h. ich kann mich mit der registrierten Email nicht einloggen. Leider.
Infos dazu habe ich dir zukommen lassen. Danke vorab!

**Comment by DuelistRag3** [comment]
vielen dank :)

**Comment by DuelistRag3** [comment]
Dein account ist gepurged und du kannst dich neu registrieren
